### ISSUE TITLE
Colons are evil!

### ISSUE THREAD

**Issue by jackfirth** [bennn/trivial#6]
I'll be the first to say it - I don't want to deal with colon suffixes.

The signatures and types of this library makes them mostly drop in replacements. But due to the choice of colon suffixes, I can't just add `(require trivial)` and hunt down type errors, I've got to manually replace my uses of the functions. Wouldn't just relying on the existence of `prefix-in` be enough? Banish the colons I say!

**Comment by bennn** [comment]
Good point about not wanting to edit old code. Especially for arithmetic. 

Would you settle for `(require trivial/no-colon)`?
#7

**Comment by jackfirth** [comment]
Yes, that's great! Thank you for your part in fighting against the forces of darkness and gratuitous symbolic identifier conventions.

**Comment by bennn** [comment]
:cake:
